export var patientData = [
  { "id":1,"first_name": "John", "middle_name": "Michael", "last_name": "Doe", "phone_number": "9876543210", "status": "positive" },
  { "id":2,"first_name": "Jane", "middle_name": "Elizabeth", "last_name": "Smith", "phone_number": "9123456789", "status": "negative" },
  { "id":3,"first_name": "David", "middle_name": "James", "last_name": "Brown", "phone_number": "9988776655", "status": "recovered" },
  { "id":4,"first_name": "Emily", "middle_name": "Rose", "last_name": "Johnson", "phone_number": "7778889999", "status": "positive" },
  { "id":5,"first_name": "Michael", "middle_name": "Andrew", "last_name": "Wilson", "phone_number": "8765432109", "status": "negative" },
  { "id":6,"first_name": "Sarah", "middle_name": "Grace", "last_name": "Davis", "phone_number": "9911223344", "status": "recovered" },
  { "id":7,"first_name": "Robert", "middle_name": "Henry", "last_name": "Miller", "phone_number": "9988776654", "status": "negative" },
  { "id":8,"first_name": "Sophia", "middle_name": "Marie", "last_name": "Taylor", "phone_number": "9001234567", "status": "recovered" },
  { "id":9,"first_name": "Daniel", "middle_name": "Lee", "last_name": "Anderson", "phone_number": "9101112131", "status": "positive" },
  { "id":10,"first_name": "Olivia", "middle_name": "Lynn", "last_name": "Thomas", "phone_number": "9876123456", "status": "negative" },
  { "id":11,"first_name": "James", "middle_name": "Oliver", "last_name": "Jackson", "phone_number": "8123456789", "status": "recovered" },
  { "id":12,"first_name": "Ava", "middle_name": "Fay", "last_name": "White", "phone_number": "9145678901", "status": "positive" },
  { "id":13,"first_name": "Ethan", "middle_name": "Paul", "last_name": "Harris", "phone_number": "9887766554", "status": "negative" },
  { "id":14,"first_name": "Mason", "middle_name": "Jack", "last_name": "Clark", "phone_number": "9321456789", "status": "recovered" },
  { "id":15,"first_name": "Chloe", "middle_name": "Grace", "last_name": "Lewis", "phone_number": "9678901234", "status": "negative" },
  {"id":16, "first_name": "Benjamin", "middle_name": "David", "last_name": "Walker", "phone_number": "8045678912", "status": "recovered" },
  {"id":17, "first_name": "Amelia", "middle_name": "Charlotte", "last_name": "Allen", "phone_number": "9345678910", "status": "positive" },
  {"id":18, "first_name": "William", "middle_name": "Jack", "last_name": "Young", "phone_number": "9812345678", "status": "negative" },
  {"id":19, "first_name": "Lucas", "middle_name": "Timothy", "last_name": "King", "phone_number": "9801234567", "status": "recovered" },
  {"id":20, "first_name": "Harper", "middle_name": "Noelle", "last_name": "Scott", "phone_number": "8999887766", "status": "positive" },
  // { "first_name": "Alexander", "middle_name": "Joseph", "last_name": "Green", "phone_number": "+1-555-321-9876", "status": "negative" },
  // { "first_name": "Liam", "middle_name": "Benjamin", "last_name": "Adams", "phone_number": "+1-555-654-1235", "status": "recovered" },
  // { "first_name": "Isabella", "middle_name": "Victoria", "last_name": "Nelson", "phone_number": "+1-555-765-6543", "status": "positive" },
  // { "first_name": "Jacob", "middle_name": "Matthew", "last_name": "Carter", "phone_number": "+1-555-432-8765", "status": "negative" },
  // { "first_name": "Zoe", "middle_name": "Grace", "last_name": "Mitchell", "phone_number": "+1-555-543-9876", "status": "recovered" },
  // { "first_name": "Megan", "middle_name": "Elizabeth", "last_name": "Perez", "phone_number": "+1-555-321-8765", "status": "positive" },
  // { "first_name": "Henry", "middle_name": "George", "last_name": "Roberts", "phone_number": "+1-555-654-2345", "status": "negative" },
  // { "first_name": "Grace", "middle_name": "Ann", "last_name": "Hernandez", "phone_number": "+1-555-234-5679", "status": "recovered" },
  // { "first_name": "Samuel", "middle_name": "Kyle", "last_name": "Gonzalez", "phone_number": "+1-555-765-9877", "status": "positive" },
  // { "first_name": "Aidan", "middle_name": "Matthew", "last_name": "Reed", "phone_number": "+1-555-876-5433", "status": "negative" },
  // { "first_name": "Charlotte", "middle_name": "Diane", "last_name": "Stewart", "phone_number": "+1-555-432-1234", "status": "recovered" },
  // { "first_name": "Jack", "middle_name": "Andrew", "last_name": "Morris", "phone_number": "+1-555-321-5678", "status": "positive" },
  // { "first_name": "Ella", "middle_name": "Mae", "last_name": "Rogers", "phone_number": "+1-555-654-4321", "status": "negative" },
  // { "first_name": "Christopher", "middle_name": "Joseph", "last_name": "Reyes", "phone_number": "+1-555-876-8902", "status": "recovered" },
  // { "first_name": "Sebastian", "middle_name": "Cole", "last_name": "Cook", "phone_number": "+1-555-432-0987", "status": "positive" },
  // { "first_name": "Grace", "middle_name": "Sophia", "last_name": "Graham", "phone_number": "+1-555-654-7654", "status": "negative" },
  // { "first_name": "Evelyn", "middle_name": "Sage", "last_name": "Mendoza", "phone_number": "+1-555-321-2345", "status": "recovered" },
  // { "first_name": "Joseph", "middle_name": "Francis", "last_name": "Baker", "phone_number": "+1-555-765-4322", "status": "positive" },
  // { "first_name": "Victoria", "middle_name": "Marie", "last_name": "Barnes", "phone_number": "+1-555-432-1090", "status": "negative" },
  // { "first_name": "Elijah", "middle_name": "Dylan", "last_name": "Perez", "phone_number": "+1-555-654-6789", "status": "recovered" },
  // { "first_name": "Maddox", "middle_name": "Christian", "last_name": "Bailey", "phone_number": "+1-555-432-1237", "status": "positive" },
  // { "first_name": "Mila", "middle_name": "Ava", "last_name": "Sanchez", "phone_number": "+1-555-678-2345", "status": "negative" },
  // { "first_name": "Nathan", "middle_name": "Wyatt", "last_name": "Collins", "phone_number": "+1-555-234-7654", "status": "recovered" },
  // { "first_name": "Eli", "middle_name": "Jaxon", "last_name": "James", "phone_number": "+1-555-765-1234", "status": "positive" },
  // { "first_name": "Madison", "middle_name": "Elyse", "last_name": "Foster", "phone_number": "+1-555-987-1230", "status": "negative" },
  // { "first_name": "Hunter", "middle_name": "Carson", "last_name": "Gibson", "phone_number": "+1-555-432-3456", "status": "recovered" },
  // { "first_name": "Lily", "middle_name": "Sophia", "last_name": "West", "phone_number": "+1-555-234-9876", "status": "positive" },
  // { "first_name": "Mason", "middle_name": "Cole", "last_name": "Burns", "phone_number": "+1-555-321-6543", "status": "negative" },
  // { "first_name": "Maya", "middle_name": "Reagan", "last_name": "Howard", "phone_number": "+1-555-987-6541", "status": "recovered" },
  // { "first_name": "Asher", "middle_name": "Grey", "last_name": "Scott", "phone_number": "+1-555-432-6789", "status": "positive" },
  // { "first_name": "Natalie", "middle_name": "Maeve", "last_name": "Allen", "phone_number": "+1-555-678-2349", "status": "negative" },
  // { "first_name": "Oliver", "middle_name": "James", "last_name": "Wright", "phone_number": "+1-555-765-4323", "status": "recovered" },
  // { "first_name": "Sophie", "middle_name": "Katherine", "last_name": "Mitchell", "phone_number": "+1-555-654-1236", "status": "positive" },
  // { "first_name": "Aidan", "middle_name": "Riley", "last_name": "Perez", "phone_number": "+1-555-876-5437", "status": "negative" },
  // { "first_name": "Jordan", "middle_name": "Louis", "last_name": "Reid", "phone_number": "+1-555-432-2341", "status": "recovered" },
  // { "first_name": "Abigail", "middle_name": "Annabelle", "last_name": "Morgan", "phone_number": "+1-555-234-6789", "status": "positive" },
  // { "first_name": "Ian", "middle_name": "Reed", "last_name": "Ross", "phone_number": "+1-555-987-6542", "status": "negative" },
  // { "first_name": "Ella", "middle_name": "Harper", "last_name": "Morris", "phone_number": "+1-555-765-3214", "status": "recovered" },
  // { "first_name": "Isaac", "middle_name": "Graham", "last_name": "Hall", "phone_number": "+1-555-654-9872", "status": "positive" },
  // { "first_name": "Nora", "middle_name": "Belle", "last_name": "Murphy", "phone_number": "+1-555-432-7654", "status": "negative" },
  // { "first_name": "Ethan", "middle_name": "Samuel", "last_name": "Russell", "phone_number": "+1-555-234-6781", "status": "recovered" },
  // { "first_name": "Dylan", "middle_name": "Elias", "last_name": "Griffith", "phone_number": "+1-555-765-2349", "status": "positive" },
  // { "first_name": "Charlotte", "middle_name": "Leah", "last_name": "Reed", "phone_number": "+1-555-876-4322", "status": "negative" },
  // { "first_name": "Matthew", "middle_name": "David", "last_name": "Harris", "phone_number": "+1-555-432-7655", "status": "recovered" },
  // { "first_name": "Grayson", "middle_name": "Thomas", "last_name": "Bell", "phone_number": "+1-555-987-1238", "status": "positive" },
  // { "first_name": "Lillian", "middle_name": "Violet", "last_name": "Hughes", "phone_number": "+1-555-234-5430", "status": "negative" },
  // { "first_name": "Oliver", "middle_name": "Ryan", "last_name": "Hunt", "phone_number": "+1-555-654-3456", "status": "recovered" }
]

